[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "univ_prop"
version = "0.4.0"
dependencies = ["numpy>=1.24"]

[tool.setuptools.packages.find]
where = ["src"]    

